{'alpha': 1.0, 'est': 'br', 'hist_agg': 'median', 'l1_ratio': 0.2987518728, 'n_cases': 24107, 'n_features': 67, 'n_games': 6}
SVD did not converge
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/Users/delano/working/python_misc/ledona/__init__.py", line 19, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 562, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 776, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 756, in calculate\n    **extra_kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 470, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 893, in search\n    n_calls=self._iterations, n_random_starts=self._bayes_init_pts)\n', '  File "/Users/delano/working/fantasy/venv/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/Users/delano/working/fantasy/venv/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 869, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'alpha': 0.01, 'est': 'br', 'hist_agg': 'none', 'l1_ratio': 0.0547551423, 'n_cases': 16451, 'n_features': 319, 'n_games': 5}
SVD did not converge
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/Users/delano/working/python_misc/ledona/__init__.py", line 19, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 562, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 776, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 756, in calculate\n    **extra_kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 470, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 893, in search\n    n_calls=self._iterations, n_random_starts=self._bayes_init_pts)\n', '  File "/Users/delano/working/fantasy/venv/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/Users/delano/working/fantasy/venv/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 869, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


