{'alpha': 0.01, 'est': 'br', 'hist_agg': 'median', 'l1_ratio': 0.8019306396, 'n_cases': 24642, 'n_features': 79, 'n_games': 1}
Ran out of input
['  File "scripts/meval.sc", line 10, in <module>\n    do_meval.process_cmd_line()\n', '  File "/Users/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/Users/delano/working/python_misc/ledona/slack.py", line 131, in wrapper_notify\n    result = func(*args, **kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 598, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 800, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 779, in calculate\n    **extra_kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 467, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 978, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/Users/delano/working/fantasy/venv/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/Users/delano/working/fantasy/venv/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 936, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


