{'colsample_bytree': 0.8621040442, 'gamma': 463, 'hist_agg': 'median', 'learning_rate': 0.1745253659, 'max_depth': 9, 'min_child_weight': 8, 'n_cases': 24651, 'n_features': 54, 'n_games': 6, 'rounds': 150, 'subsample': 0.5070885497}
Cannot create random sample of size 36976 because after dropping Nan from y only 23639 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'colsample_bytree': 0.881606351, 'gamma': 7, 'hist_agg': 'mean', 'learning_rate': 0.1890659017, 'max_depth': 6, 'min_child_weight': 3, 'n_cases': 22543, 'n_features': 54, 'n_games': 3, 'rounds': 140, 'subsample': 0.6263654691}
Cannot create random sample of size 33814 because after dropping Nan from y only 24848 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'colsample_bytree': 0.8701054354, 'gamma': 3593, 'hist_agg': 'none', 'learning_rate': 0.1281489198, 'max_depth': 8, 'min_child_weight': 3, 'n_cases': 16810, 'n_features': 201, 'n_games': 4, 'rounds': 105, 'subsample': 0.8784475562}
Cannot create random sample of size 25215 because after dropping Nan from y only 24438 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'colsample_bytree': 0.9147648775, 'gamma': 21, 'hist_agg': 'none', 'learning_rate': 0.1586640122, 'max_depth': 6, 'min_child_weight': 2, 'n_cases': 28687, 'n_features': 54, 'n_games': 1, 'rounds': 123, 'subsample': 0.7109686475}
Cannot create random sample of size 43030 because after dropping Nan from y only 25668 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'colsample_bytree': 0.730457766, 'gamma': 0, 'hist_agg': 'none', 'learning_rate': 0.1466021124, 'max_depth': 9, 'min_child_weight': 10, 'n_cases': 18353, 'n_features': 250, 'n_games': 5, 'rounds': 110, 'subsample': 0.5545707735}
Cannot create random sample of size 27529 because after dropping Nan from y only 24034 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'colsample_bytree': 0.7804953962, 'gamma': 1291, 'hist_agg': 'median', 'learning_rate': 0.0700770371, 'max_depth': 6, 'min_child_weight': 8, 'n_cases': 25204, 'n_features': 54, 'n_games': 4, 'rounds': 119, 'subsample': 0.5238794196}
Cannot create random sample of size 37806 because after dropping Nan from y only 24438 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


