{'est': 'rforest', 'hist_agg': 'none', 'n_cases': 21364, 'n_features': 152, 'n_games': 3, 'rf_crit': 'mae', 'rf_max_depth': 500, 'rf_max_features': 'log2', 'rf_min_samples_leaf': 164, 'rf_trees': 17}
Cannot create random sample of size 32046 because after dropping Nan from y only 24848 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'est': 'rforest', 'hist_agg': 'median', 'n_cases': 26993, 'n_features': 54, 'n_games': 2, 'rf_crit': 'mse', 'rf_max_depth': 500, 'rf_max_features': 'sqrt', 'rf_min_samples_leaf': 34, 'rf_trees': 7}
Cannot create random sample of size 40489 because after dropping Nan from y only 25261 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'est': 'rforest', 'hist_agg': 'none', 'n_cases': 30823, 'n_features': 201, 'n_games': 4, 'rf_crit': 'mse', 'rf_max_depth': 0, 'rf_max_features': 'sqrt', 'rf_min_samples_leaf': 143, 'rf_trees': 21}
Cannot create random sample of size 46234 because after dropping Nan from y only 24438 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


{'est': 'rforest', 'hist_agg': 'mean', 'n_cases': 21763, 'n_features': 54, 'n_games': 5, 'rf_crit': 'mse', 'rf_max_depth': 500, 'rf_max_features': 'log2', 'rf_min_samples_leaf': 84, 'rf_trees': 24}
Cannot create random sample of size 32644 because after dropping Nan from y only 24034 cases remained.
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/home/delano/working/python_misc/ledona/__init__.py", line 21, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 564, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 791, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/engine.py", line 770, in calculate\n    **extra_kwargs)\n', '  File "/home/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 472, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 955, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/home/delano/working/fantasy/venv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/home/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 917, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


