{'est': 'rforest', 'hist_agg': 'median', 'n_cases': 31824, 'n_features': 67, 'n_games': 5, 'rf_crit': 'mse', 'rf_max_depth': 0, 'rf_max_features': 'log2', 'rf_min_samples_leaf': 74, 'rf_trees': 15}
Ran out of input
['  File "scripts/meval.sc", line 3, in <module>\n    do_meval.process_cmd_line()\n', '  File "/Users/delano/working/python_misc/ledona/__init__.py", line 22, in wrapper\n    result = timed_func(*args, **kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 567, in process_cmd_line\n    result = calc_engine.run_evaluation(eval_func)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 799, in run_evaluation\n    calc_def_id=calc_def_id)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/engine.py", line 778, in calculate\n    **extra_kwargs)\n', '  File "/Users/delano/working/fantasy/fantasy_py/calculation/regression/exe/do_meval.py", line 475, in eval_func\n    \'db\': meta_info.db_path.split(os.sep)[-1]})\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 959, in search\n    n_calls=n_calls, n_random_starts=n_random_starts)\n', '  File "/Users/delano/working/fantasy/venv-pyenv-3.6/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 228, in gp_minimize\n    callback=callback, n_jobs=n_jobs)\n', '  File "/Users/delano/working/fantasy/venv-pyenv-3.6/lib/python3.6/site-packages/skopt/optimizer/base.py", line 248, in base_minimize\n    next_y = func(next_x)\n', '  File "/Users/delano/working/fantasy/fantasy_py/util/hyper_param_tuning.py", line 921, in skopt_func\n    self.errors[flattened_hp_dict] = (ex, traceback.format_stack())\n']
----------------------------------------


